services:
  mongo:
    image: mongo:7.0-rc
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-saatnya-id:/data/db

volumes:
  mongo-saatnya-id:
